### ISSUE TITLE
How to undo the removing tokens

### ISSUE THREAD

**Issue by C2J0** [MaciejGorczyca/ChallengesAreEvil#7]
So I initially got this to remove the tokens so I could later put only one up instead of being forced to have 3, but unfortunately not only can I not put any tokens up, but the titles are removed as well.  I've tried uninstalling/reinstalling and everything and still the client just freezes when I try to click out of the token/title screen to save it.  Is there any way to undo this?

**Comment by MaciejGorczyca** [comment]
There are no changes to the app. I can still successfully remove and re-select tokens. The app is only one line of code actually, here it is
https://github.com/MaciejGorczyca/ChallengesAreEvil/blob/3bd3b36ea3c972f435248f994a7d7ab285145edd/ChallengesAreEvil/ChallengesAreEvil.cs#L47
And it literally zeroes your selection. If the client doesn't let you select something then it is issue with the client.

If something breaks then it is because of Riot, so go send them a ticket, message them on social platforms or send email to their management and tell them how awful challenges are!
